# Generated by Django 5.0.2 on 2024-02-12 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_registration_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='addblog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('meassage', models.CharField(blank=True, max_length=10000, null=True)),
            ],
        ),
    ]
